on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Install Dependency
        run: pnpm i --frozen-lockfile
        working-directory: ./front
      - name: Lint
        run: pnpm lint
        working-directory: ./front
