on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install:  |
            - cwd: ./front
      - name: Lint
        run: pnpm lint
        working-directory: ./front
